apiVersion: apps/v1
kind: Deployment
metadata:
  name: opal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opal
  template:
    metadata:
      labels:
        app: opal
    spec:
      containers:
        - name: opal
          image: permitio/opal:latest
          ports:
            - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: opal
spec:
  selector:
    app: opal
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
